Public class Arpractice
{
    public void createPrecite()
    {
    System.debug('Hello, it s practice line');
    System.debug('Hello, it s practice line2 test');
    }
    // Added by Meenakshi
    public void createPreciteTest()
    {
    System.debug('Hello, it s practice line Test');
    }
    // Added by Meenakshi
    public void createPreciteTest1()
    {
    System.debug('Hello, it s practice line Test');
    }
    public void toDemo()
    {
    System.debug('Hello, its demo');
    }
}